# file: secret_config.yaml

jupyterhub:
  proxy:
    secretToken: 8ab358498cadf3e05db75341c3ba9b41d65e565433a6ec17020afe31f2dd7806
  hub:
    extraEnv:
      OAUTH2_AUTHORIZE_URL: https://iris-iam.stfc.ac.uk/authorize
      OAUTH2_TOKEN_URL: https://iris-iam.stfc.ac.uk/token
      OAUTH_CALLBACK_URL: http://128.232.227.125/hub/oauth_callback

  auth:
    type: custom
    custom:
      className: oauthenticator.generic.GenericOAuthenticator
      config:
        login_service: "IRIS IAM"
        client_id: "75dc9e2a-3c08-436e-b110-d710d1e3c530"
        client_secret: "AJ5u1mnTIZKpwwqi0vZW-meb-Uob5ekJxQ3lD0VyL7d3hdiSM4f-dmmV7ULrLDQx7KQH6G8ZyQRdcf3s703WQoc"
        token_url: https://iris-iam.stfc.ac.uk/token
        userdata_url: https://iris-iam.stfc.ac.uk/userinfo
        userdata_method: GET
        userdata_params: {'state': 'state'}
        username_key: preferred_username
        oauth_callback_url: "http://128.232.227.125/hub/oauth_callback"

  # comment this out if not using github authentication
  #auth:
  #  type: github
  #  github:
  #    clientId: 61704a204a9acc4bf994
  #    clientSecret: 62af9625af3bc4dca3c2009a0996905a97b42555
  #    callbackUrl: "http://128.232.227.125/hub/oauth_callback"
  #  scopes:
  #    - "read:user"
  #  admin:
  #    access: true
  #    users:
  #      - brtknr
