# file: secret_config.yaml

jupyterhub:
  proxy:
    secretToken: 8ab358498cadf3e05db75341c3ba9b41d65e565433a6ec17020afe31f2dd7806

  # comment this out if not using github authentication
  auth:
    type: github
    github:
      clientId: 61704a204a9acc4bf994
      clientSecret: 62af9625af3bc4dca3c2009a0996905a97b42555
      callbackUrl: "http://128.232.227.125/hub/oauth_callback"
    scopes:
      - "read:user"
    admin:
      access: true
      users:
        - brtknr
